In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [ ]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [ ]:
data2 = requests.get(standings_url)

In [ ]:
soup = BeautifulSoup(data2.text)

In [ ]:
standings_tb = soup.select("table.stats_table")[0]

In [ ]:
links = standings_tb.find_all('a')

In [ ]:
#get all the links in the table
links = [l.get("href") for l in links]

In [ ]:
#Look for just the links to the team pages and store them
links = [l for l in links if '/squads/' in l]

In [ ]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [ ]:
team_urls

['https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats',
 'https://fbref.com/en/squads/18bb7c10/Arsenal-Stats',
 'https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats',
 'https://fbref.com/en/squads/19538871/Manchester-United-Stats',
 'https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
 'https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/8602292d/Aston-Villa-Stats',
 'https://fbref.com/en/squads/cd051869/Brentford-Stats',
 'https://fbref.com/en/squads/fd962109/Fulham-Stats',
 'https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats',
 'https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats',
 'https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats',
 'https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats',
 'https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats',
 'https://fbref.com/en/squads/d3fd31cc/Everton-Stats',
 'https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats',
 'https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats',
 'https://fbref.com/en/squads/33c895d4/Southampton-Stats']

In [ ]:
ars_url = team_urls[0]

In [ ]:
data = requests.get(ars_url)

In [ ]:
matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

In [ ]:
soup = BeautifulSoup(data.text)

In [ ]:
links = soup.find_all('a')

In [ ]:
links = [l.get("href") for l in links]

In [ ]:
links = [l for l in links if l and 'all_comps/shooting/' in l]

In [ ]:
#Get the html page for the corresponding team's shooting stats
data = requests.get(f"https://fbref.com{links[0]}")

In [ ]:
#read the data into a pandas df
shooting = pd.read_html(data.text, match="Shooting")[0]

type(shooting)

pandas.core.frame.DataFrame

In [ ]:
#Remove multi-level index
shooting.columns = shooting.columns.droplevel()

In [ ]:
team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist","FK","PK","PKatt","xG"]], on="Date" )

In [ ]:
team_data

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,xG_y
0,2022-07-30,17:00,Community Shield,FA Community Shield,Sat,Neutral,L,1.0,3.0,Liverpool,...,Craig Pawson,Match Report,NaN,14,8,NaN,NaN,0,0,NaN
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,Michael Oliver,Match Report,NaN,13,1,18.7,1.0,1,1,2.2
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,David Coote,Match Report,NaN,19,7,17.5,0.0,0,0,1.7
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,Jarred Gillett,Match Report,NaN,21,10,16.2,1.0,0,0,2.1
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,Darren England,Match Report,NaN,18,5,14.1,0.0,0,0,2.2
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,Paul Tierney,Match Report,NaN,17,9,14.8,0.0,0,0,3.3
6,2022-09-03,17:30,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,Aston Villa,...,Simon Hooper,Match Report,NaN,13,4,16.8,1.0,0,0,2.1
7,2022-09-06,21:00,Champions Lg,Group stage,Tue,Away,W,4.0,0.0,es Sevilla,...,Davide Massa,Match Report,NaN,24,9,16.9,1.0,0,0,3.6
8,2022-09-14,20:00,Champions Lg,Group stage,Wed,Home,W,2.0,1.0,de Dortmund,...,Daniele Orsato,Match Report,NaN,12,3,17.3,0.0,0,0,1.0
9,2022-09-17,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,0.0,Wolves,...,Anthony Taylor,Match Report,NaN,16,7,19.4,0.0,0,0,1.1
10,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Home,W,6.0,3.0,Manchester Utd,...,Michael Oliver,Match Report,NaN,22,9,14.2,1.0,0,0,3.2
11,2022-10-05,20:00,Champions Lg,Group stage,Wed,Home,W,5.0,0.0,dk FC Copenhagen,...,Donatas Rumšas,Match Report,NaN,29,15,19.2,1.0,1,1,4.3
12,2022-10-08,15:00,Premier League,Matchweek 10,Sat,Home,W,4.0,0.0,Southampton,...,Andy Madley,Match Report,NaN,21,8,13.9,0.0,0,0,2.4
13,2022-10-11,18:45,Champions Lg,Group stage,Tue,Away,D,0.0,0.0,dk FC Copenhagen,...,Artur Dias,Match Report,NaN,13,3,21.7,0.0,0,1,1.6
14,2022-10-16,16:30,Premier League,Matchweek 11,Sun,Away,L,0.0,1.0,Liverpool,...,Anthony Taylor,Match Report,NaN,16,6,18.4,0.0,0,0,1.0
15,2022-10-22,15:00,Premier League,Matchweek 13,Sat,Home,W,3.0,1.0,Brighton,...,Craig Pawson,Match Report,NaN,9,3,15.0,0.0,1,1,1.6
16,2022-10-25,21:00,Champions Lg,Group stage,Tue,Away,D,0.0,0.0,de Dortmund,...,Davide Massa,Match Report,NaN,7,2,19.8,0.0,0,1,1.2
17,2022-10-29,12:30,Premier League,Matchweek 14,Sat,Away,W,1.0,0.0,Leicester City,...,Robert Jones,Match Report,NaN,15,5,20.8,1.0,0,0,1.0
18,2022-11-02,20:00,Champions Lg,Group stage,Wed,Home,W,3.0,1.0,es Sevilla,...,Orel Grinfeeld,Match Report,NaN,21,7,15.9,0.0,0,0,2.0
19,2022-11-05,15:00,Premier League,Matchweek 15,Sat,Home,W,2.0,1.0,Fulham,...,Darren England,Match Report,NaN,15,4,18.1,1.0,1,1,2.1
20,2022-11-09,20:00,EFL Cup,Third round,Wed,Home,W,2.0,0.0,Chelsea,...,Simon Hooper,Match Report,NaN,18,9,NaN,NaN,0,0,NaN
21,2022-11-12,12:30,Premier League,Matchweek 16,Sat,Home,L,1.0,2.0,Brentford,...,Peter Bankes,Match Report,NaN,29,6,20.9,0.0,0,0,1.6
22,2022-12-22,20:00,EFL Cup,Fourth round,Thu,Home,W,3.0,2.0,Liverpool,...,David Coote,Match Report,NaN,18,9,NaN,NaN,0,0,NaN
23,2022-12-28,20:00,Premier League,Matchweek 17,Wed,Away,W,3.0,1.0,Leeds United,...,Stuart Attwell,Match Report,NaN,26,9,16.0,0.0,0,0,4.3
24,2022-12-31,15:00,Premier League,Matchweek 18,Sat,Home,D,1.0,1.0,Everton,...,Andy Madley,Match Report,NaN,16,3,15.4,0.0,0,0,1.7
25,2023-01-05,20:00,Premier League,Matchweek 19,Thu,Away,W,1.0,0.0,Chelsea,...,Paul Tierney,Match Report,NaN,12,3,16.0,0.0,0,0,2.1
26,2023-01-08,16:30,FA Cup,Third round proper,Sun,Home,W,4.0,0.0,Chelsea,...,Robert Jones,Match Report,NaN,9,7,NaN,NaN,2,2,NaN
27,2023-01-11,20:00,EFL Cup,Quarter-finals,Wed,Away,L,0.0,2.0,Southampton,...,Peter Bankes,Match Report,NaN,7,0,NaN,NaN,0,0,NaN
28,2023-01-14,12:30,Premier League,Matchweek 20,Sat,Away,L,1.0,2.0,Manchester Utd,...,Stuart Attwell,Match Report,NaN,5,1,19.2,0.0,0,0,0.6
29,2023-01-19,20:00,Premier League,Matchweek 7,Thu,Home,W,4.0,2.0,Tottenham,...,Simon Hooper,Match Report,NaN,16,6,16.3,1.0,0,0,2.3
30,2023-01-22,14:00,Premier League,Matchweek 21,Sun,Home,W,3.0,0.0,Wolves,...,David Coote,Match Report,NaN,12,5,14.8,0.0,1,1,2.8
31,2023-01-27,20:00,FA Cup,Fourth round proper,Fri,Home,W,1.0,0.0,Arsenal,...,Paul Tierney,Match Report,NaN,8,3,NaN,NaN,0,0,NaN
32,2023-02-05,16:30,Premier League,Matchweek 22,Sun,Away,L,0.0,1.0,Tottenham,...,Andy Madley,Match Report,NaN,15,5,17.7,1.0,0,0,1.3
33,2023-02-12,16:30,Premier League,Matchweek 23,Sun,Home,W,3.0,1.0,Aston Villa,...,Robert Jones,Match Report,NaN,16,7,15.4,1.0,1,1,3.3
34,2023-02-15,19:30,Premier League,Matchweek 12,Wed,Away,W,3.0,1.0,Arsenal,...,Anthony Taylor,Match Report,NaN,9,5,12.1,0.0,0,0,1.8
35,2023-02-18,15:00,Premier League,Matchweek 24,Sat,Away,D,1.0,1.0,Nott'ham Forest,...,Graham Scott,Match Report,NaN,23,6,18.0,2.0,0,0,2.4
36,2023-02-22,21:00,Champions Lg,Round of 16,Wed,Away,D,1.0,1.0,de RB Leipzig,...,Serdar Gözübüyük,Match Report,Leg 1 of 2,12,3,15.9,1.0,0,0,1.2
37,2023-02-25,17:30,Premier League,Matchweek 25,Sat,Away,W,4.0,1.0,Bournemouth,...,Paul Tierney,Match Report,NaN,20,5,15.3,1.0,0,0,2.4
38,2023-02-28,20:00,FA Cup,Fifth round proper,Tue,Away,W,3.0,0.0,Bristol City,...,Andre Marriner,Match Report,NaN,16,6,NaN,NaN,0,0,NaN
39,2023-03-04,12:30,Premier League,Matchweek 26,Sat,Home,W,2.0,0.0,Newcastle Utd,...,Simon Hooper,Match Report,NaN,11,3,15.8,2.0,0,0,1.3
40,2023-03-11,17:30,Premier League,Matchweek 27,Sat,Away,W,1.0,0.0,Crystal Palace,...,Robert Jones,Match Report,NaN,13,3,19.0,1.0,1,1,2.1
41,2023-03-14,20:00,Champions Lg,Round of 16,Tue,Home,W,7.0,0.0,de RB Leipzig,...,Slavko Vinčič,Match Report,Leg 2 of 2; Manchester City won,22,14,13.1,0.0,1,1,4.2
42,2023-03-18,17:45,FA Cup,Quarter-finals,Sat,Home,W,6.0,0.0,Burnley,...,John Brooks,Match Report,NaN,20,10,NaN,NaN,0,0,NaN
43,2023-04-01,12:30,Premier League,Matchweek 29,Sat,Home,W,4.0,1.0,Liverpool,...,Simon Hooper,Match Report,NaN,17,8,14.5,1.0,0,0,2.9
44,2023-04-08,17:30,Premier League,Matchweek 30,Sat,Away,W,4.0,1.0,Southampton,...,Robert Jones,Match Report,NaN,12,7,13.2,0.0,1,1,2.9
45,2023-04-11,20:00,Champions Lg,Quarter-finals,Tue,Home,W,3.0,0.0,de Bayern Munich,...,Jesús Gil,Match Report,Leg 1 of 2,17,9,14.5,0.0,0,0,1.8
46,2023-04-15,17:30,Premier League,Matchweek 31,Sat,Home,W,3.0,1.0,Leicester City,...,Darren England,Match Report,NaN,11,3,17.8,0.0,1,1,1.6
47,2023-04-19,21:00,Champions Lg,Quarter-finals,Wed,Away,D,1.0,1.0,de Bayern Munich,...,Clément Turpin,Match Report,Leg 2 of 2; Manchester City won,6,2,21.0,0.0,0,1,1.3
48,2023-04-22,16:45,FA Cup,Semi-finals,Sat,Neutral,W,3.0,0.0,Sheffield Utd,...,Stuart Attwell,Match Report,NaN,14,4,NaN,NaN,1,1,NaN
49,2023-04-26,20:00,Premier League,Matchweek 33,Wed,Home,W,4.0,1.0,Arsenal,...,Michael Oliver,Match Report,NaN,14,9,15.9,0.0,0,0,2.5
50,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,W,2.0,1.0,Fulham,...,Simon Hooper,Match Report,NaN,11,8,14.1,0.0,1,1,2.5
51,2023-05-03,20:00,Premier League,Matchweek 28,Wed,Home,W,3.0,0.0,West Ham,...,John Brooks,Match Report,NaN,16,7,16.3,0.0,0,0,2.3
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,...,Andy Madley,Match Report,NaN,17,6,18.7,2.0,0,1,2.6
53,2023-05-09,21:00,Champions Lg,Semi-finals,Tue,Away,D,1.0,1.0,es Real Madrid,...,Artur Dias,Match Report,Leg 1 of 2,10,6,21.7,0.0,0,0,0.5
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3.0,0.0,Everton,...,Anthony Taylor,Match Report,NaN,9,4,19.3,2.0,0,0,0.8
55,2023-05-17,20:00,Champions Lg,Semi-finals,Wed,Home,W,4.0,0.0,es Real Madrid,...,Szymon Marciniak,Match Report,Leg 2 of 2; Manchester City won,16,8,16.1,1.0,0,0,2.8

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Referee,Match Report,Notes
0,2022-07-30,17:00,Community Shield,FA Community Shield,Sat,Neutral,L,1.0,3.0,Liverpool,NaN,NaN,57.0,NaN,Rúben Dias,4-3-3,Craig Pawson,Match Report,NaN
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,2.2,0.5,75.0,62443.0,İlkay Gündoğan,4-3-3,Michael Oliver,Match Report,NaN
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,1.7,0.1,67.0,53453.0,İlkay Gündoğan,4-2-3-1,David Coote,Match Report,NaN
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,2.1,1.8,69.0,52258.0,İlkay Gündoğan,4-3-3,Jarred Gillett,Match Report,NaN
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,2.2,0.1,74.0,53112.0,Kevin De Bruyne,4-2-3-1,Darren England,Match Report,NaN

In [ ]:
shooting.shape

(57, 26)

In [1]:
years = list(range(2023,2020,-1))
all_matches=[]

In [2]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [5]:

for year in years:
    
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    standings_tb = soup.select('table.stats_table')[0]

    links = [l.get("href") for l in standings_tb.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com{previous_season}"
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")

        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist","FK","PK","PKatt","xG"]], on="Date")
        except ValueError:
            continue
        
        team_data = team_data[team_data["Comp"] == "Premier League"] 
        
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(10)

In [13]:
len(all_matches)

60

In [14]:
df = pd.concat(all_matches)

In [16]:
df.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Notes,Sh,SoT,Dist,FK,PK,PKatt,xG_y,Season,Team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2.2,2023,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,NaN,19.0,7.0,17.5,0.0,0.0,0.0,1.7,2023,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2.1,2023,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2.2,2023,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,NaN,17.0,9.0,14.8,0.0,0.0,0.0,3.3,2023,Manchester City

In [18]:
df.columns = [c.lower() for c in df.columns]

In [19]:
#Drop any duplicate columns, I accidently scraped two expected goals columns so I am simply removing one of them
df = df.drop('xg_y', axis=1)

df = df.rename(columns={'xg_x':'xg'})

In [ ]:
df["opp_num"] = df["opponent"].astype("category").cat.codes

In [ ]:
df["hour"] = df["time"].str.replace(":.+","", regex=True).astype("int")

In [ ]:
df["venue_num"] = df["venue"].astype("category").cat.codes

In [ ]:
df["result_factor"]= (df["result"] == "W").astype("int")

In [ ]:
#Convert date to numerical variable
df["date"] = pd.to_datetime(df["date"])
df["day_code"] = df["date"].dt.dayofweek

In [ ]:
#Sort final dataframe by date
df = df.sort_values(by="date")

In [ ]:
df.to_csv("prem_2020_2023_cleaned.csv")